import { create } from 'zustand'
import type { PatientProfileData, Patient } from '../types'
import { mockPatientProfile } from '../data/mockPatientProfile'

interface PatientStore {
  patients: Patient[]
  profiles: Record<string, PatientProfileData>
  addPatient: (profile: PatientProfileData) => void
  getProfile: (id: string) => PatientProfileData | undefined
}

const seedPatients: PatientProfileData[] = [
  mockPatientProfile,
  {
    id: 'anita-lopez',
    fullName: 'Anita Lopez',
    mrn: '555-012',
    gender: 'female',
    phone: '(555) 012-3456',
    email: 'anita.l@email.com',
    address: '123 Main Street',
    city: 'San Francisco',
    state: 'CA',
    zipCode: '94102',
    communicationMode: 'phone',
    timingSlots: ['8AM - 10AM', '10AM - 12PM'],
    status: 'Active',
    photoUrl: '',
    primaryDiagnosis: 'Recovery from Surgery',
    secondaryDiagnoses: [],
    assignedPt: 'Dr. James Wilson',
    assignedPtImg: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200',
    emergencyContact: { name: 'Maria Lopez', relation: 'Sister', phone: '(555) 012-3457' },
    insurance: { provider: 'Aetna', memberId: 'AET555012', groupNumber: 'GRP-5550' },
    visits: { scheduled: 6, completed: 4, missed: 0 },
    notes: { date: 'OCT 22, 2023', author: 'COORDINATOR', content: 'Patient is recovering well from surgery. Good support system at home.' },
  },
  {
    id: 'robert-jenkins',
    fullName: 'Robert Jenkins',
    mrn: '412-990',
    gender: 'male',
    phone: '(555) 234-5678',
    email: 'robert.j@email.com',
    address: '456 Oak Avenue',
    city: 'San Francisco',
    state: 'CA',
    zipCode: '94107',
    communicationMode: 'email',
    timingSlots: ['10AM - 12PM', '1PM - 3PM'],
    status: 'Active',
    photoUrl: '',
    primaryDiagnosis: 'Knee Replacement Recovery',
    secondaryDiagnoses: ['Osteoarthritis', 'High Blood Pressure'],
    assignedPt: 'Sarah Thorne',
    assignedPtImg: 'https://i.pravatar.cc/150?u=sarah',
    emergencyContact: { name: 'Linda Jenkins', relation: 'Wife', phone: '(555) 876-5432' },
    insurance: { provider: 'Blue Shield PPO', memberId: 'BS412990', groupNumber: 'GRP-8823' },
    visits: { scheduled: 8, completed: 6, missed: 1 },
    notes: { date: 'OCT 20, 2023', author: 'COORDINATOR', content: 'Patient is responding well to physical therapy. Home environment is suitable for recovery.' },
  },
  {
    id: 'alice-khowani',
    fullName: 'Alice Khowani',
    mrn: '701-223',
    gender: 'female',
    phone: '(555) 345-6789',
    email: 'alice.k@email.com',
    address: '789 Pine Street',
    city: 'San Francisco',
    state: 'CA',
    zipCode: '94110',
    communicationMode: 'phone',
    timingSlots: ['8AM - 10AM'],
    status: 'Inactive',
    photoUrl: '',
    primaryDiagnosis: 'Stroke Rehabilitation',
    secondaryDiagnoses: ['Diabetes Type 2', 'High Cholesterol'],
    assignedPt: 'Unassigned',
    assignedPtImg: '',
    emergencyContact: { name: 'David Khowani', relation: 'Son', phone: '(555) 654-3210' },
    insurance: { provider: 'Medicare Part A', memberId: 'MED701223', groupNumber: 'GRP-4412' },
    visits: { scheduled: 15, completed: 12, missed: 2 },
    notes: { date: 'SEP 28, 2023', author: 'COORDINATOR', content: 'Patient is making steady progress with speech and mobility therapy.' },
  },
  {
    id: 'sarah-connor',
    fullName: 'Sarah Connor',
    mrn: '666-789',
    gender: 'female',
    phone: '(555) 345-6789',
    email: 'sarah.c@email.com',
    address: '555 Tech Boulevard',
    city: 'San Francisco',
    state: 'CA',
    zipCode: '94115',
    communicationMode: 'phone',
    timingSlots: ['10AM - 12PM'],
    status: 'Active',
    photoUrl: '',
    primaryDiagnosis: 'Post-operative Recovery',
    secondaryDiagnoses: ['Asthma'],
    assignedPt: 'John Smith',
    assignedPtImg: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=200',
    emergencyContact: { name: 'Kyle Reese', relation: 'Brother', phone: '(555) 345-6790' },
    insurance: { provider: 'Cigna', memberId: 'CIG666789', groupNumber: 'GRP-6667' },
    visits: { scheduled: 5, completed: 5, missed: 0 },
    notes: { date: 'OCT 25, 2023', author: 'COORDINATOR', content: 'Patient is fully recovered and ready for discharge.' },
  },
  {
    id: 'marcus-bennett',
    fullName: 'Marcus Bennett',
    mrn: '902-115',
    gender: 'male',
    phone: '(555) 456-7890',
    email: 'marcus.b@email.com',
    address: '321 Cedar Lane',
    city: 'San Francisco',
    state: 'CA',
    zipCode: '94114',
    communicationMode: 'text',
    timingSlots: ['1PM - 3PM', '3PM - 5PM'],
    status: 'Active',
    photoUrl: '',
    primaryDiagnosis: 'Cardiac Rehabilitation',
    secondaryDiagnoses: ['Heart Disease', 'Obesity'],
    assignedPt: 'Dr. Julian Vance',
    assignedPtImg: 'https://i.pravatar.cc/150?u=julian',
    emergencyContact: { name: 'Emma Bennett', relation: 'Daughter', phone: '(555) 321-0987' },
    insurance: { provider: 'UnitedHealthcare', memberId: 'UHC902115', groupNumber: 'GRP-6678' },
    visits: { scheduled: 10, completed: 8, missed: 0 },
    notes: { date: 'OCT 18, 2023', author: 'COORDINATOR', content: 'Patient is highly motivated and compliant with treatment plan.' },
  },
  {
    id: 'marcus-brooks',
    fullName: 'Marcus Brooks',
    mrn: '777-001',
    gender: 'male',
    phone: '(555) 777-0001',
    email: 'marcus.brooks@email.com',
    address: '100 Market Street',
    city: 'San Francisco',
    state: 'CA',
    zipCode: '94105',
    communicationMode: 'phone',
    timingSlots: ['8AM - 10AM', '10AM - 12PM'],
    status: 'Active',
    photoUrl: '',
    primaryDiagnosis: 'Post-surgical Recovery',
    secondaryDiagnoses: [],
    assignedPt: 'Unassigned',
    assignedPtImg: '',
    emergencyContact: { name: 'Lisa Brooks', relation: 'Wife', phone: '(555) 777-0002' },
    insurance: { provider: 'Medicare Part B', memberId: 'MED777001', groupNumber: 'GRP-7770' },
    visits: { scheduled: 8, completed: 2, missed: 0 },
    notes: { date: 'NOV 01, 2023', author: 'COORDINATOR', content: 'Initial evaluation completed. Pending PT assignment.' },
  },
  {
    id: 'elena-langford',
    fullName: 'Elena Langford',
    mrn: '777-002',
    gender: 'female',
    phone: '(555) 777-0003',
    email: 'elena.langford@email.com',
    address: '200 Ocean Avenue',
    city: 'Beverly Hills',
    state: 'CA',
    zipCode: '90210',
    communicationMode: 'email',
    timingSlots: ['10AM - 12PM', '1PM - 3PM'],
    status: 'Active',
    photoUrl: '',
    primaryDiagnosis: 'Lower Back Pain',
    secondaryDiagnoses: ['Sciatica'],
    assignedPt: 'Dr. Marcus Chen',
    assignedPtImg: 'https://i.pravatar.cc/150?u=marcus',
    emergencyContact: { name: 'Tom Langford', relation: 'Husband', phone: '(555) 777-0004' },
    insurance: { provider: 'Blue Shield PPO', memberId: 'BS777002', groupNumber: 'GRP-7771' },
    visits: { scheduled: 10, completed: 5, missed: 1 },
    notes: { date: 'OCT 30, 2023', author: 'COORDINATOR', content: 'Patient is responding well to PT for lower back pain.' },
  },
  {
    id: 'sarah-jenkins',
    fullName: 'Sarah Jenkins',
    mrn: '777-003',
    gender: 'female',
    phone: '(555) 777-0005',
    email: 'sarah.jenkins@email.com',
    address: '300 Broadway',
    city: 'San Francisco',
    state: 'CA',
    zipCode: '94105',
    communicationMode: 'phone',
    timingSlots: ['8AM - 10AM'],
    status: 'Active',
    photoUrl: '',
    primaryDiagnosis: 'Upper Body Weakness',
    secondaryDiagnoses: ['Arthritis'],
    assignedPt: 'Unassigned',
    assignedPtImg: '',
    emergencyContact: { name: 'Mike Jenkins', relation: 'Brother', phone: '(555) 777-0006' },
    insurance: { provider: 'Aetna', memberId: 'AET777003', groupNumber: 'GRP-7772' },
    visits: { scheduled: 6, completed: 3, missed: 0 },
    notes: { date: 'NOV 02, 2023', author: 'COORDINATOR', content: 'Needs OT evaluation for upper body strength training.' },
  },
  {
    id: 'james-miller',
    fullName: 'James Miller',
    mrn: '777-004',
    gender: 'male',
    phone: '(555) 777-0007',
    email: 'james.miller@email.com',
    address: '400 Pine Street',
    city: 'San Francisco',
    state: 'CA',
    zipCode: '94102',
    communicationMode: 'phone',
    timingSlots: ['10AM - 12PM'],
    status: 'Lead',
    photoUrl: '',
    primaryDiagnosis: 'Post-surgery PT Evaluation',
    secondaryDiagnoses: [],
    assignedPt: 'Unassigned',
    assignedPtImg: '',
    emergencyContact: { name: 'Sarah Miller', relation: 'Wife', phone: '(555) 777-0008' },
    insurance: { provider: 'Medicare Part A', memberId: 'MED777004', groupNumber: 'GRP-7773' },
    visits: { scheduled: 0, completed: 0, missed: 0 },
    notes: { date: 'NOV 05, 2023', author: 'COORDINATOR', content: 'New referral. Pending evaluation.' },
  },
]

function profileToPatient(p: PatientProfileData): Patient {
  return {
    id: p.id,
    name: p.fullName,
    initials: p.fullName.split(' ').map(n => n[0]).join(''),
    mrn: p.mrn,
    dov: p.status === 'Lead' ? 'Today' : 'Ongoing',
    status: p.status,
    statusVariant: (p.status === 'Lead' ? 'default' : p.status === 'Active' ? 'info' : 'secondary') as Patient['statusVariant'],
    assignedPt: p.assignedPt,
    assignedPtImg: p.assignedPtImg || null,
  }
}

const initialPatients = seedPatients.map(profileToPatient)
const initialProfiles = Object.fromEntries(seedPatients.map(p => [p.id, p]))

export const usePatientStore = create<PatientStore>((set, get) => ({
  patients: initialPatients,
  profiles: initialProfiles,

  addPatient: (profile) => set((state) => ({
    patients: [...state.patients, profileToPatient(profile)],
    profiles: { ...state.profiles, [profile.id]: profile },
  })),

  getProfile: (id) => get().profiles[id],
}))
